install: true

 language: scala

# scala :
#  - 2.10.6

jdk: oraclejdk8

script :
 - sbt clean
 - sbt compile
 - sbt 'universal:packageZipTarball'
 - cd puckExtendJ/target/universal
 - cp `ls -rt | tail -1` ../../../website/puck.tgz
 - ls -R

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: website/
  on:
    branch: master

